### ISSUE TITLE
5 minute read on how to write Swift Documentation

### ISSUE THREAD

**Issue by godwinpang** [Honey4Groceries/Honey4Groceries#15]
Documentation is a very important part of creating a maintainable and healthy codebase. Although it may seem tedious/pointless at times, it is imperative that you write documentation and I promise that it will be a lot nicer than PA comments.

Please comment down below once you have read the link below.
Dhruv Chaddah - done reading
[`Swift Documentation`](https://nshipster.com/swift-documentation/)

**Comment by xuryann** [comment]
Ryan Xu - done reading
